AI ML ASSIGNMENT NO - 14 

name - shahid ahmad khan 
college - maanav school of polytechnic 


Create a 2D array of shape (5, 6) filled with random integers between 10 and 100.
Print the following:
Shape of the array
Total number of elements (size)
Data type (dtype)


In [1]:
import numpy as np 

# create a 2d array of shape (5, 6) filled with random integers between 10 and 100
arr = np.random.randint(10, 101, size=(5, 6))

# display the array 
print("Array: \n", arr)

# print array properties
print("Shape of the array: ", arr.shape)
print("Total number of elements (size): ", arr.size)
print("Data type (dtype): ", arr.dtype)



Array: 
 [[43 14 86 95 46 16]
 [43 20 98 95 46 25]
 [45 21 62 30 19 19]
 [13 14 88 15 93 61]
 [39 63 94 15 54 80]]
Shape of the array:  (5, 6)
Total number of elements (size):  30
Data type (dtype):  int32


np.random.randint().
Print:
Minimum value and its index (argmin)
Maximum value and its index (argmax)
Sum of all elements
Mean and Standard Deviation

In [2]:
import numpy as np 

# genrate the 1d array of 20 random numbers between 1 and 50 
arr = np.random.randint(1, 51, size=20)

# display the array 
print("array: \n", arr)

# minimum value and its index 
print("\minimum value:",arr.min())
print("index of minimum value:",arr.argmin())

# maximum value and its index
print("\maximum value:",arr.max())
print("index of maximum value:",arr.argmax())

# sum of all elements 
print("sum of all elements:", arr.sum())

# mean and standard deviation 
print("mean:", arr.mean())
print("standard deviation:", arr.std())




array: 
 [33  9 31 25 35 48  4 46 37 44 12 21 18  6  8 37 32 29 16 35]
\minimum value: 4
index of minimum value: 6
\maximum value: 48
index of maximum value: 5
sum of all elements: 526
mean: 26.3
standard deviation: 13.439121995130483


 Create a 4x5 matrix of random integers between 20 and 80.
For the entire matrix, print:
Minimum and maximum value
Sum of all elements
Mean and Standard Deviation
Then print the sum of each row and each column.

In [3]:
import numpy as np 

# create a 4x5 matrix of random integers between 20 and 80 
matrix = np.random.randint(20, 81, size=(4, 5))

# display the matrix 
print("Matrix: \n", matrix)

# entire matrix statetics 
print("Minimum value:",matrix.min())
print("Maximum value:",matrix.max())
print("Sum of all elements:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard deviation:", matrix.std())

# sum of each row and column
print("Sum of each row: \n", matrix.sum(axis=1))
print("Sum of each column: \n", matrix.sum(axis=0))







Matrix: 
 [[41 38 78 38 51]
 [66 20 48 27 40]
 [59 40 77 63 77]
 [55 72 55 26 53]]
Minimum value: 20
Maximum value: 78
Sum of all elements: 1024
Mean: 51.2
Standard deviation: 17.089763017666453
Sum of each row: 
 [246 201 316 261]
Sum of each column: 
 [221 170 258 154 221]


 Create a 1D array containing numbers from 1 to 24 using np.arange(). Reshape it into (4, 6) Reshape it into (3, 8) Reshape it into (2, 3, 4) (3D array) Print all reshaped arrays with their shapes


In [4]:
import numpy as np

# create a 1D array containing numbers from 1 to 24 
arr = np.arange(1, 25)

# reshape into (4, 6)
arr1 = arr.reshape(4, 6)

# reshape into (3 , 8)
arr2 = arr.reshape(3, 8)

# reshape into (2, 3, 4) 
arr3 = arr.reshape(2, 3, 4)

# print all reshaped arrays with their shapes
print("original array:")
print(arr)
print("shape:",arr.shape)

print("nreshaped array (4, 6):")
print(arr1)
print("shape:",arr1.shape)

print("nreshaped array (3, 8):")
print(arr2)
print("shape:",arr2.shape)

print("nreshaped array (2, 3, 4):")
print(arr3)
print("shape:",arr3.shape)



original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
shape: (24,)
nreshaped array (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)
nreshaped array (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
shape: (3, 8)
nreshaped array (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)


Create the following array:  Extract first row
Extract last column
Extract center 2x2 submatrix
Extract all even numbers from the array using boolean indexing

In [5]:
import numpy as np 

# create the array 
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])


# display the array 
print("Array:")
print(arr)

# extract first row 
print("first row:")
print(arr[0])

# extract last column 
print("last column:")
print(arr[:, -1])

# extract center 2x2 submatrix 
print("center 2x2 submatrix:")
print(arr[1:3, 1:3])

# extract all even numbers from the array using boolean indexing 
print("even numbers:")
print(arr[arr % 2 == 0])


Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
first row:
[10 20 30 40]
last column:
[ 40  80 120]
center 2x2 submatrix:
[[ 60  70]
 [100 110]]
even numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


Create a 5x5 matrix of random integers between 1 and 100.
Print the diagonal elements
Print elements greater than 50
Replace all elements less than 30 with 0
Print the modified array


In [6]:
import numpy as np 

# create a 5x5 matrix of random integers between 1 and 100
arr = np.random.randint(1, 101, (5, 5))

# display the original array 
print("Original array:")
print(arr)

# print diagonal elements 
print("Diagonal elements:")
print(np.diag(arr))

# print elements greater than 50
print("Elements greater than 50:")
print(arr[arr > 50])

# replace all elements less than 30 with 0
arr[arr < 30] = 0

# print the modified array 
print("Modified array:")
print(arr)

Original array:
[[66 53 73 14 53]
 [50 52 17 65 29]
 [85 59 65 16 25]
 [12 72 67 74 61]
 [ 7 78  4 62 18]]
Diagonal elements:
[66 52 65 74 18]
Elements greater than 50:
[66 53 73 53 52 65 85 59 65 72 67 74 61 78 62]
Modified array:
[[66 53 73  0 53]
 [50 52  0 65  0]
 [85 59 65  0  0]
 [ 0 72 67 74 61]
 [ 0 78  0 62  0]]


Create two arrays:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
Perform and print:
Addition, Subtraction, Multiplication, Division
Element-wise power (**)  Modulo operation (%)


In [7]:
import numpy as np 

# create two arrays 
a = np.array([10, 20, 30, 40]) 
b = np.array([1, 2, 3, 4])

# addition 
print("Addition:")
print(a + b)

# subtraction 
print("Subtraction:")
print(a - b)

# multiplication 
print("Multiplication:")
print(a * b)

# division 
print("Division:")
print(a / b)

# element-wise power (**) 
print("Element-wise power:")
print(a ** b)

# modulo operation (%) 
print("Modulo operation:")
print(a % b)


Addition:
[11 22 33 44]
Subtraction:
[ 9 18 27 36]
Multiplication:
[ 10  40  90 160]
Division:
[10. 10. 10. 10.]
Element-wise power:
[     10     400   27000 2560000]
Modulo operation:
[0 0 0 0]


Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform:
Element-wise multiplication (*)
Matrix multiplication (@ or np.dot())
Print both results and explain the difference in comments.


In [ ]:
import numpy as np 

# create two 3x3 matrices 
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication (*)
elementwise_mult = A * B
print("Element-wise Multiplication:")
print(elementwise_mult)

# matrix multiplication (@ or np.dot())
matrix_mult = np.dot(A, B)
print("Matrix Multiplication using @ operator:")
print(matrix_mult)
print("Matrix Multiplication using np.dot():")
print(matrix_mult)

# print the matrices 
print("matrix A:")
print(A)

print("matrix B:")
print(B)

print("Element-wise multiplication:")
print(elementwise_mult)

print("matrix multiplication:")
print(matrix_mult)

# Difference:
# (*) multiplies corresponding elements of both matrices.
# (@) or np.dot() performs matrix multiplication
# by multiplying rows of A with columns of B.





Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication using @ operator:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix Multiplication using np.dot():
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Generate a 6x6 matrix of random numbers using np.random.randn().
Print its shape, size, and dtype.
Find the index of the maximum and minimum value.
Extract the top-left 3x3 submatrix.
Replace all negative numbers with their absolute value.
Print the mean of the modified matrix.


In [10]:
import numpy as np 

# genrate a 6x6 matrix of random numbers 
arr = np.random.randn(6,6) 

# display the orignal matrix
print("Original Matrix:")
print(arr)

# print the shape, size and dtype of the array
print("Shape:", arr.shape)
print("Size:", arr.size)
print("dtype:", arr.dtype)

# find the index of maximum and minimum value 
print("index of the maximum value:", np.argmax(arr))
print("index of the minimum value:", np.argmin(arr))

# extract the top-left 3x3 submatrix
print("Top-left 3x3 submatrix:")
print(arr[:3, :3])

# replace all negative numbers with their absolute value 
arr = np.abs(arr)

# display the modified matrix
print("Modified Matrix:")
print(arr)

# print the mean of the modified matrix 
print("Mean:", np.mean(arr))


Original Matrix:
[[ 0.03563293  0.46882125 -0.92526084  0.59856206  1.0088324  -2.05093018]
 [ 1.60939557  1.84948604 -0.05199134 -0.24984842 -1.94968779 -0.71455845]
 [-0.05912951  1.06251247  1.24186266 -1.02408387 -0.17831838  0.14386318]
 [ 0.44912663 -1.30262543 -0.14018562 -3.05086654  0.8298839  -0.3887789 ]
 [-0.13418823  0.45651206 -0.74032523  0.06394755  2.08403171  0.69820788]
 [ 0.38419595  0.05970945 -1.29381439 -1.03207568 -0.37961847  1.53943091]]
Shape: (6, 6)
Size: 36
dtype: float64
index of the maximum value: 28
index of the minimum value: 21
Top-left 3x3 submatrix:
[[ 0.03563293  0.46882125 -0.92526084]
 [ 1.60939557  1.84948604 -0.05199134]
 [-0.05912951  1.06251247  1.24186266]]
Modified Matrix:
[[0.03563293 0.46882125 0.92526084 0.59856206 1.0088324  2.05093018]
 [1.60939557 1.84948604 0.05199134 0.24984842 1.94968779 0.71455845]
 [0.05912951 1.06251247 1.24186266 1.02408387 0.17831838 0.14386318]
 [0.44912663 1.30262543 0.14018562 3.05086654 0.8298839  0.3887789

 Create a NumPy-based Student Marks Analyzer:
Generate a 2D array of shape (10 students × 5 subjects) with random marks
between 30 and 100.
Print the array.
For each student, calculate total marks and average.
Find the student with highest and lowest total marks (use argmax/argmin).
Calculate overall class mean and standard deviation.
Reshape the array if needed and demonstrate indexing to extract marks of top
3 students.
Add proper comments explaining each step.

In [14]:
import numpy as np 

# genrate a 2d array of shape (10,5)
# 10 students and 5 subjects with random marks between 30 and 100
marks = np.random.randint(30, 101, size=(10, 5))

# display the marks of all students 
print("Marks of all students:")
print(marks)

# calculate total marks for each student
total_marks = np.sum(marks, axis=1)

# calculate average marks for each student
average_marks = np.mean(total_marks)

# display the total marks and average marks for each student
print("Total marks of all students:")
print(total_marks)
print("Average marks of all students:")
print(average_marks)

# find the student with higest total marks 
highest_mark_student = np.argmax(total_marks)

# find the student with lowest total marks 
lowest_mark_student = np.argmin(total_marks)

print("student with higest total marks:", highest_mark_student)

print("student with lowest total marks:", lowest_mark_student)

# calculate overall class mean 
class_mean = np.mean(marks)

# calculate overall class standard deviation
class_std= np.std(marks)

print("Overall class mean:")
print("class mean:")

print("Overall class standard deviation:")
print("class_std_dev")

# Sort students based on total marks in descending order
top_students = np.argsort(total_marks)[::-1]

print("Top 3 students based on total marks:")
print(top_students)

# Extract marks of the top 3 students using indexing
top_3_marks = marks[top_students[:3]]

# Reshape the array into 5 x 10 (Demonstration of reshape)
reshaped_marks = marks.reshape(5, 10)

print("Reshaped array:")
print(reshaped_marks)












Marks of all students:
[[41 95 87 56 86]
 [91 32 32 59 92]
 [43 98 45 68 97]
 [81 53 32 98 62]
 [76 97 96 41 85]
 [46 46 94 58 71]
 [58 38 44 61 76]
 [56 80 40 73 30]
 [50 32 70 33 96]
 [34 37 82 57 73]]
Total marks of all students:
[365 306 351 326 395 315 277 279 281 283]
Average marks of all students:
317.8
student with higest total marks: 4
student with lowest total marks: 6
Overall class mean:
class mean:
Overall class standard deviation:
class_std_dev
Top 3 students based on total marks:
[4 0 2 3 5 1 9 8 7 6]
Reshaped array:
[[41 95 87 56 86 91 32 32 59 92]
 [43 98 45 68 97 81 53 32 98 62]
 [76 97 96 41 85 46 46 94 58 71]
 [58 38 44 61 76 56 80 40 73 30]
 [50 32 70 33 96 34 37 82 57 73]]
